{
  "hash": "c34ef486827aaa91fd201a73faafe3bb",
  "result": {
    "engine": "knitr",
    "markdown": "---\nshow-solutions: false\n---\n\n# Assignment 1 {.unnumbered}\n\nThis assignment focuses on the foundations of the linear model: \n\n+ matrix representation, \n+ least squares estimation, \n+ projection\n+ basic inference. \n\n::: {.callout-note title=\"Instructions\"}\n\n- Submit both your source file (`.qmd` or `.Rmd`) and the rendered HTML or PDF file.\n- Name your source file as `A1_LastName_FirstName.qmd` or `A1_LastName_FirstName.Rmd`.\n- Clearly label every question and subpart.\n- Type all mathematical work using LaTeX.\n- Include all R code used to obtain your answers.\n- Your document must render from beginning to end without error.\n- Do not submit screenshots of code, R output, or mathematical derivations.\n- Round numerical answers to three decimal places when appropriate.\n- For True/False questions, enter only `T` or `F`.\n- For short-answer questions, one or two clear sentences are sufficient unless a derivation is requested.\n\n::: \n\nThe total value of the assignment is [**40**].\n\n## Question 1: Matrix Representation of the Linear Model [8]\n\nConsider the simple linear regression model\n\n$$\nY_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i,\n\\qquad i=1,\\ldots,5,\n$$\n\nwith the following observed data:\n\n| $i$ | $x_i$ | $Y_i$ |\n|---:|---:|---:|\n| 1 | 0 | 2 |\n| 2 | 1 | 4 |\n| 3 | 2 | 5 |\n| 4 | 3 | 8 |\n| 5 | 4 | 9 |\n\n### (a) [2]\n\nWhich of the following is the correct design matrix $\\mathbf{X}$?\n\n- [ ] **A.**\n\n$$\n\\begin{pmatrix}\n0 & 2\\\\\n1 & 4\\\\\n2 & 5\\\\\n3 & 8\\\\\n4 & 9\n\\end{pmatrix}\n$$\n\n- [ ] **B.**\n\n$$\n\\begin{pmatrix}\n1 & 0\\\\\n1 & 1\\\\\n1 & 2\\\\\n1 & 3\\\\\n1 & 4\n\\end{pmatrix}\n$$\n\n- [ ] **C.**\n\n$$\n\\begin{pmatrix}\n0 & 1\\\\\n1 & 1\\\\\n2 & 1\\\\\n3 & 1\\\\\n4 & 1\n\\end{pmatrix}\n$$\n\n- [ ] **D.**\n\n$$\n\\begin{pmatrix}\n1 & 2\\\\\n1 & 4\\\\\n1 & 5\\\\\n1 & 8\\\\\n1 & 9\n\\end{pmatrix}\n$$\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:** B\n\n:::\n\n### (b) [2]\n\nFill in the following table.\n\n| Quantity | Dimension / Rank |\n|:---|:---|\n| $\\mathbf{Y}$ | `___` |\n| $\\mathbf{X}$ | `___` |\n| $\\boldsymbol{\\beta}$ | `___` |\n| $\\operatorname{rank}(\\mathbf{X})$ | `___` |\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\n| Quantity | Dimension / Rank |\n|:---|:---|\n| $\\mathbf{Y}$ | $5\\times 1$ |\n| $\\mathbf{X}$ | $5\\times 2$ |\n| $\\boldsymbol{\\beta}$ | $2\\times 1$ |\n| $\\operatorname{rank}(\\mathbf{X})$ | $2$ |\n\n:::\n\n### (c) [2]\n\nWhich pair is correct?\n\n- [ ] **A.**\n\n$$\n\\mathbf{X}^\\top\\mathbf{X}\n=\n\\begin{pmatrix}\n5 & 10\\\\\n10 & 30\n\\end{pmatrix},\n\\qquad\n\\mathbf{X}^\\top\\mathbf{Y}\n=\n\\begin{pmatrix}\n28\\\\\n77\n\\end{pmatrix}\n$$\n\n- [ ] **B.**\n\n$$\n\\mathbf{X}^\\top\\mathbf{X}\n=\n\\begin{pmatrix}\n5 & 5\\\\\n5 & 30\n\\end{pmatrix},\n\\qquad\n\\mathbf{X}^\\top\\mathbf{Y}\n=\n\\begin{pmatrix}\n28\\\\\n74\n\\end{pmatrix}\n$$\n\n- [ ] **C.**\n\n$$\n\\mathbf{X}^\\top\\mathbf{X}\n=\n\\begin{pmatrix}\n30 & 10\\\\\n10 & 5\n\\end{pmatrix},\n\\qquad\n\\mathbf{X}^\\top\\mathbf{Y}\n=\n\\begin{pmatrix}\n77\\\\\n28\n\\end{pmatrix}\n$$\n\n- [ ] **D.**\n\n$$\n\\mathbf{X}^\\top\\mathbf{X}\n=\n\\begin{pmatrix}\n5 & 10\\\\\n10 & 20\n\\end{pmatrix},\n\\qquad\n\\mathbf{X}^\\top\\mathbf{Y}\n=\n\\begin{pmatrix}\n28\\\\\n77\n\\end{pmatrix}\n$$\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:** A\n\n:::\n\n### (d) [2]\n\nAssume\n\n$$\n\\mathbb{E}[\\boldsymbol{\\varepsilon}] = \\mathbf{0},\n\\qquad\n\\operatorname{Var}(\\boldsymbol{\\varepsilon})=\\sigma^2\\mathbf{I}_5.\n$$\n\nFor each statement, enter `T` or `F`.\n\n| Statement | T/F |\n|:---|:---:|\n| $\\mathbb{E}[\\mathbf{Y}] = \\mathbf{X}\\boldsymbol{\\beta}$ | `___` |\n| $\\operatorname{Var}(\\mathbf{Y}) = \\sigma^2\\mathbf{I}_5$ | `___` |\n| $\\mathbb{E}[\\mathbf{Y}] = \\mathbf{0}$ | `___` |\n| The five errors all have variance $\\sigma^2$ | `___` |\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\n| Statement | T/F |\n|:---|:---:|\n| $\\mathbb{E}[\\mathbf{Y}] = \\mathbf{X}\\boldsymbol{\\beta}$ | T |\n| $\\operatorname{Var}(\\mathbf{Y}) = \\sigma^2\\mathbf{I}_5$ | T |\n| $\\mathbb{E}[\\mathbf{Y}] = \\mathbf{0}$ | F |\n| The five errors all have variance $\\sigma^2$ | T |\n\n:::\n\n## Question 2: Least Squares and Projection [12]\n\nContinue using the data and design matrix from Question 1.\n\n### (a) [4]\n\nStarting from\n\n$$\nS(\\boldsymbol{\\beta})\n=\n(\\mathbf{Y}-\\mathbf{X}\\boldsymbol{\\beta})^\\top\n(\\mathbf{Y}-\\mathbf{X}\\boldsymbol{\\beta}),\n$$\n\nderive the normal equations\n\n$$\n\\mathbf{X}^\\top\\mathbf{X}\\hat{\\boldsymbol{\\beta}}\n=\n\\mathbf{X}^\\top\\mathbf{Y},\n$$\n\nand then state the OLS estimator when $\\mathbf{X}$ has full column rank.\n\nKeep your derivation concise.\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\nExpanding,\n\n$$\nS(\\boldsymbol{\\beta})\n=\n\\mathbf{Y}^\\top\\mathbf{Y}\n-\n2\\boldsymbol{\\beta}^\\top\\mathbf{X}^\\top\\mathbf{Y}\n+\n\\boldsymbol{\\beta}^\\top\\mathbf{X}^\\top\\mathbf{X}\\boldsymbol{\\beta}.\n$$\n\nDifferentiating,\n\n$$\n\\frac{\\partial S(\\boldsymbol{\\beta})}{\\partial\\boldsymbol{\\beta}}\n=\n-2\\mathbf{X}^\\top\\mathbf{Y}\n+\n2\\mathbf{X}^\\top\\mathbf{X}\\boldsymbol{\\beta}.\n$$\n\nSetting the derivative equal to zero gives\n\n$$\n\\mathbf{X}^\\top\\mathbf{X}\\hat{\\boldsymbol{\\beta}}\n=\n\\mathbf{X}^\\top\\mathbf{Y}.\n$$\n\nHence,\n\n$$\n\\boxed{\n\\hat{\\boldsymbol{\\beta}}\n=\n(\\mathbf{X}^\\top\\mathbf{X})^{-1}\n\\mathbf{X}^\\top\\mathbf{Y}\n}.\n$$\n\n:::\n\n### (b) [3]\n\nUsing the quantities from Question 1, compute\n\n$$\n\\hat{\\boldsymbol{\\beta}}\n=\n\\begin{pmatrix}\n\\hat{\\beta}_0\\\\\n\\hat{\\beta}_1\n\\end{pmatrix}.\n$$\n\nFill in the blanks:\n\n$$\n\\hat{\\beta}_0 = \\underline{\\hspace{2cm}},\n\\qquad\n\\hat{\\beta}_1 = \\underline{\\hspace{2cm}}.\n$$\n\nHence,\n\n$$\n\\hat{Y}\n=\n\\underline{\\hspace{2cm}}\n+\n\\underline{\\hspace{2cm}}x.\n$$\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\n$$\n\\hat{\\beta}_0=1.4,\n\\qquad\n\\hat{\\beta}_1=2.1,\n$$\n\nso\n\n$$\n\\boxed{\\hat{Y}=1.4+2.1x}.\n$$\n\n:::\n\n### (c) [2]\n\nFor the least squares residual vector\n\n$$\n\\mathbf{e}\n=\n\\mathbf{Y}-\\hat{\\mathbf{Y}},\n$$\n\nwhich statement must be true?\n\n- [ ] **A.** $\\mathbf{X}\\mathbf{e}=\\mathbf{0}$\n\n- [ ] **B.** $\\mathbf{X}^\\top\\mathbf{e}=\\mathbf{0}$\n\n- [ ] **C.** $\\mathbf{e}^\\top\\mathbf{e}=0$\n\n- [ ] **D.** $\\mathbf{H}\\mathbf{e}=\\mathbf{e}$\n\nIn one sentence, explain the geometric meaning of your choice.\n\n**Your explanation:**  \n`____________________________________________________________`\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:** B\n\nThe residual vector is orthogonal to the column space of $\\mathbf{X}$.\n\n:::\n\n### (d) [3]\n\nFor the hat matrix\n\n$$\n\\mathbf{H}\n=\n\\mathbf{X}\n(\\mathbf{X}^\\top\\mathbf{X})^{-1}\n\\mathbf{X}^\\top,\n$$\n\nenter `T` or `F`.\n\n| Statement | T/F |\n|:---|:---:|\n| $\\mathbf{H}^\\top=\\mathbf{H}$ | `___` |\n| $\\mathbf{H}^2=\\mathbf{H}$ | `___` |\n| $\\hat{\\mathbf{Y}}=\\mathbf{H}\\mathbf{Y}$ | `___` |\n| $\\mathbf{H}$ is an orthogonal projection matrix | `___` |\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\n| Statement | T/F |\n|:---|:---:|\n| $\\mathbf{H}^\\top=\\mathbf{H}$ | T |\n| $\\mathbf{H}^2=\\mathbf{H}$ | T |\n| $\\hat{\\mathbf{Y}}=\\mathbf{H}\\mathbf{Y}$ | T |\n| $\\mathbf{H}$ is an orthogonal projection matrix | T |\n\n:::\n\n## Question 3: Distribution and Inference [12]\n\nSuppose a multiple linear regression model has $n=20$ observations and $p=3$ regression parameters. Assume\n\n$$\n\\mathbf{Y}\n\\sim\nN_{20}\n\\left(\n\\mathbf{X}\\boldsymbol{\\beta},\n\\sigma^2\\mathbf{I}_{20}\n\\right).\n$$\n\nSuppose\n\n$$\n\\hat{\\boldsymbol{\\beta}}\n=\n\\begin{pmatrix}\n2.0\\\\\n1.5\\\\\n-0.5\n\\end{pmatrix},\n$$\n\n$$\n(\\mathbf{X}^\\top\\mathbf{X})^{-1}\n=\n\\begin{pmatrix}\n0.20 & 0 & 0\\\\\n0 & 0.05 & 0\\\\\n0 & 0 & 0.08\n\\end{pmatrix},\n$$\n\nand\n\n$$\n\\mathrm{SSE}=34.\n$$\n\nUse\n\n$$\nt_{0.975,17}=2.110.\n$$\n\n### (a) [3]\n\nChoose the correct distributions.\n\nFor $\\hat{\\boldsymbol{\\beta}}$:\n\n- [ ] **A.** $N_3\\!\\left(\\mathbf{0},\\sigma^2\\mathbf{I}_3\\right)$\n\n- [ ] **B.** $N_3\\!\\left(\\boldsymbol{\\beta},\\sigma^2(\\mathbf{X}^\\top\\mathbf{X})^{-1}\\right)$\n\n- [ ] **C.** $t_{17}$\n\n- [ ] **D.** $\\chi^2_{17}$\n\nFor $\\mathrm{SSE}/\\sigma^2$:\n\n- [ ] **A.** $N(0,1)$\n\n- [ ] **B.** $t_{17}$\n\n- [ ] **C.** $\\chi^2_{17}$\n\n- [ ] **D.** $F_{3,17}$\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:** B and C\n\n:::\n\n### (b) [2]\n\nCompute\n\n$$\n\\hat{\\sigma}^2\n=\n\\frac{\\mathrm{SSE}}{n-p}.\n$$\n\n$$\n\\hat{\\sigma}^2 = \\underline{\\hspace{2cm}}.\n$$\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\n$$\n\\boxed{\\hat{\\sigma}^2=2}.\n$$\n\n:::\n\n### (c) [4]\n\nFor testing\n\n$$\nH_0:\\beta_1=0\n\\qquad\\text{versus}\\qquad\nH_1:\\beta_1\\neq0,\n$$\n\nwhere $\\beta_1$ is the second entry of $\\boldsymbol{\\beta}$, fill in the following:\n\n$$\n\\mathrm{SE}(\\hat{\\beta}_1)\n=\n\\underline{\\hspace{2cm}},\n$$\n\n$$\nt\n=\n\\underline{\\hspace{2cm}},\n$$\n\nand choose the decision:\n\n- [ ] **A.** Reject $H_0$\n\n- [ ] **B.** Fail to reject $H_0$\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\n$$\n\\mathrm{SE}(\\hat{\\beta}_1)\n=\n\\sqrt{2(0.05)}\n=\n0.3162,\n$$\n\n$$\nt\n=\n\\frac{1.5}{0.3162}\n=\n4.7434.\n$$\n\nSince $|4.7434|>2.110$, the answer is **A: Reject $H_0$**.\n\n:::\n\n### (d) [3]\n\nWhich of the following is the 95% confidence interval for $\\beta_1$?\n\n- [ ] **A.** $(0.8329,\\;2.1671)$\n\n- [ ] **B.** $(1.1838,\\;1.8162)$\n\n- [ ] **C.** $(-0.6671,\\;0.6671)$\n\n- [ ] **D.** $(0,\\;3.0000)$\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:** A\n\n:::\n\n## Question 4: Linear Regression in R [8]\n\nFor this question, use the built-in R dataset `cars`.\n\nThe variables are:\n\n- `speed`: speed of the car in miles per hour;\n- `dist`: stopping distance in feet.\n\nConsider the model\n\n$$\n\\mathrm{dist}_i\n=\n\\beta_0\n+\n\\beta_1\\mathrm{speed}_i\n+\n\\varepsilon_i.\n$$\n\nLoad the data using\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(cars)\n```\n:::\n\n\n### (a) [4]\n\nFit the model using `lm()` and complete the table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(dist ~ speed, data = cars)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = dist ~ speed, data = cars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-29.069  -9.525  -2.272   9.215  43.201 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -17.5791     6.7584  -2.601   0.0123 *  \nspeed         3.9324     0.4155   9.464 1.49e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.38 on 48 degrees of freedom\nMultiple R-squared:  0.6511,\tAdjusted R-squared:  0.6438 \nF-statistic: 89.57 on 1 and 48 DF,  p-value: 1.49e-12\n```\n\n\n:::\n:::\n\n\n| Quantity | Your answer |\n|:---|:---|\n| $\\hat{\\beta}_0$ | `___` |\n| $\\hat{\\beta}_1$ | `___` |\n\nWhich interpretation of $\\hat{\\beta}_1$ is correct?\n\n- [ ] **A.** For each 1 mph increase in speed, the stopping distance increases by exactly 3.9324 feet for every car.\n\n- [ ] **B.** For each 1 mph increase in speed, the fitted mean stopping distance increases by approximately 3.9324 feet.\n\n- [ ] **C.** The average speed increases by 3.9324 mph for every extra foot of stopping distance.\n\n- [ ] **D.** A car travelling at 0 mph has a stopping distance of 3.9324 feet.\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\n$$\n\\hat{\\beta}_0=-17.5791,\n\\qquad\n\\hat{\\beta}_1=3.9324.\n$$\n\nThe correct interpretation is **B**.\n\n:::\n\n### (b) [4]\n\nConstruct $\\mathbf{Y}$ and $\\mathbf{X}$ manually and reproduce the OLS coefficients using matrix operations.\n\nComplete the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY <- matrix(cars$dist, ncol = 1)\n\nX <- cbind(\n  1,\n  cars$speed\n)\n\n# Replace NULL with your matrix expression\nbeta_hat <- NULL\n\nbeta_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n:::\n\n\nThen report\n\n$$\n\\hat{\\boldsymbol{\\beta}}\n=\n\\begin{pmatrix}\n\\underline{\\hspace{2cm}}\\\\\n\\underline{\\hspace{2cm}}\n\\end{pmatrix}.\n$$\n\n::: {.solution .content-visible when-meta=\"show-solutions\"}\n\n**Solution:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeta_hat <- solve(t(X) %*% X) %*% t(X) %*% Y\n```\n:::\n\n\nand\n\n$$\n\\boxed{\n\\hat{\\boldsymbol{\\beta}}\n=\n\\begin{pmatrix}\n-17.5791\\\\\n3.9324\n\\end{pmatrix}\n}.\n$$\n\n:::\n\n## Grading Summary\n\n| Question | Topic | Value |\n|:---|:---|---:|\n| Question 1 | Matrix representation | 8 |\n| Question 2 | Least squares and projection | 12 |\n| Question 3 | Distribution and inference | 12 |\n| Question 4 | Regression in R | 8 |\n| **Total** |  | **40** |\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}